# Pygame screen settings
GAME_HEIGHT = 512
STATUS_HEIGHT = 64
SCREEN_HEIGHT = GAME_HEIGHT + STATUS_HEIGHT
SCREEN_WIDTH = 1024
FPS = 60

# Game settings
STARTING_LIVES = 100
TARGET_RADIUS = 32
TARGET_SHRINK = 0.1
SPAWN_TIME = 350
